name: Worldguard Custom Use
version: ${project.version}
main: com.github.thedeathlycow.worldguardcustomuse.WorldguardCustomUse
api-version: 1.16
depend: [ WorldGuard ]
authors: [ TheDeathlyCow ]
description: Allows only certains blocks to be affected by the use flag.
website: https://github.com/TheDeathlyCow
